import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { Package, AlertTriangle } from "lucide-react";
import client from "../api/client";
import PageHead from "../components/PageHead";
import Badge from "../components/Badge";
import EmptyState from "../components/EmptyState";

export default function DetailPage() {
  const { id } = useParams();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    client.get(`/batches/${id}`).then((res) => setData(res.data)).finally(() => setLoading(false));
  }, [id]);

  if (loading) return null;
  if (!data || !data.product) {
    return <div className="card"><EmptyState icon={Package} title="Record not found" desc="This product or batch could not be located." /></div>;
  }

  const { product, batch, recall, anomaly } = data;

  return (
    <>
      <PageHead eyebrow="Product / batch detail" title={product.name}
        action={<Badge status={batch ? batch.displayStatus : "ACTIVE"} />} />
      <div className="grid gap-3.5" style={{ gridTemplateColumns: "1fr 1fr" }}>
        <div className="card">
          <div className="mb-4.5">
            <div className="text-xs font-bold uppercase tracking-wide text-faint mb-2.5">Product information</div>
            <div className="kv-row"><span className="kv-label">Product ID</span><span className="kv-val lt-mono">{product.id}</span></div>
            <div className="kv-row"><span className="kv-label">Description</span><span className="kv-val text-right max-w-[220px]">{product.desc}</span></div>
            <div className="kv-row"><span className="kv-label">Manufacturer</span><span className="kv-val">{product.manufacturer}</span></div>
            <div className="kv-row"><span className="kv-label">Category</span><span className="kv-val">{product.category}</span></div>
          </div>
          {batch && (
            <div>
              <div className="text-xs font-bold uppercase tracking-wide text-faint mb-2.5">Batch information</div>
              <div className="kv-row"><span className="kv-label">Batch number</span><span className="kv-val lt-mono">{batch.batch}</span></div>
              <div className="kv-row"><span className="kv-label">Quantity</span><span className="kv-val">{batch.qty.toLocaleString()}</span></div>
              <div className="kv-row"><span className="kv-label">Manufacturing date</span><span className="kv-val">{batch.mfg}</span></div>
              <div className="kv-row"><span className="kv-label">Expiry date</span><span className="kv-val">{batch.expiry}</span></div>
              <div className="kv-row"><span className="kv-label">Generation level</span><span className="kv-val capitalize">{batch.generationLevel}-level</span></div>
            </div>
          )}
        </div>

        <div className="card">
          <div className="mb-4.5">
            <div className="text-xs font-bold uppercase tracking-wide text-faint mb-2.5">Label information</div>
            <div className="kv-row"><span className="kv-label">Labels generated</span><span className="kv-val">{batch ? batch.codesGenerated.toLocaleString() : "—"}</span></div>
            <div className="kv-row"><span className="kv-label">Labels activated</span><span className="kv-val">{batch ? batch.codesActivated.toLocaleString() : "—"}</span></div>
            <div className="kv-row"><span className="kv-label">Generated by</span><span className="kv-val">{batch?.createdBy || "—"}</span></div>
          </div>
          <div className="mb-4.5">
            <div className="text-xs font-bold uppercase tracking-wide text-faint mb-2.5">Recall information</div>
            {recall ? (
              <>
                <div className="kv-row"><span className="kv-label">Reason</span><span className="kv-val text-right max-w-[220px]">{recall.reason}</span></div>
                <div className="kv-row"><span className="kv-label">Recalled by</span><span className="kv-val">{recall.recalledBy}</span></div>
                <div className="kv-row"><span className="kv-label">Recall date</span><span className="kv-val">{recall.date?.slice(0, 10)}</span></div>
              </>
            ) : <div className="text-[13px] text-muted">No recall associated with this batch.</div>}
          </div>
          {anomaly && (
            <div>
              <div className="text-xs font-bold uppercase tracking-wide text-faint mb-2.5">Anomaly flag</div>
              <div className="flex items-start gap-3">
                <div className="w-[30px] h-[30px] rounded-md flex items-center justify-center flex-shrink-0 bg-red-tint">
                  <AlertTriangle size={15} className="text-red" />
                </div>
                <div className="text-[13px] text-text">{anomaly.text}</div>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
