import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Package, AlertTriangle, ArrowLeft } from "lucide-react";
import client from "../api/client";
import PageHead from "../components/PageHead";
import EmptyState from "../components/EmptyState";

export default function DetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [activationHistory, setActivationHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  
  async function loadDetail() {
  setLoading(true);

  try {
    const [detailRes, historyRes] = await Promise.all([
      client.get(`/batches/${id}`),
      client.get("/dispatch/history"),
    ]);

    setData(detailRes.data);

    const batchNo = detailRes.data?.batch?.batch;

    const history = historyRes.data || [];

    setActivationHistory(
      history.filter((item) => item.batch === batchNo)
    );
  } finally {
    setLoading(false);
  }
}

useEffect(() => {
  loadDetail();
}, [id]);


  if (loading) return null;
  if (!data || !data.product) {
    return <div className="card"><EmptyState icon={Package} title="Record not found" desc="This product or batch could not be located." /></div>;
  }

  const { product, batch, recall, anomaly } = data;

  return (
    <>
      <PageHead eyebrow="Product / batch detail" title={product.name}
      action={
        <button className="btn btn-outline" onClick={() => navigate("/batches")} > <ArrowLeft size={14} />Back</button>
      }
      />
      <div className="grid gap-3.5" style={{ gridTemplateColumns: "1fr 1fr" }}>
        <div className="card">
          <div className="mb-4.5">
            <div className="text-xs font-bold uppercase tracking-wide text-faint mb-2.5">Product information</div>
            <div className="kv-row"> <span className="kv-label">Product name</span> <span className="kv-val">{product.name || "—"}</span> </div>
            <div className="kv-row"><span className="kv-label">Description</span><span className="kv-val text-right max-w-[220px]">{product.desc}</span></div>
            <div className="kv-row"><span className="kv-label">Manufacturer</span><span className="kv-val">{product.manufacturer}</span></div>
            <div className="kv-row"><span className="kv-label">Category</span><span className="kv-val">{product.category}</span></div>
          </div>
          {batch && (
            <>
            <div>
              <div className="text-xs font-bold uppercase tracking-wide text-faint mb-2.5">Batch information</div>
              <div className="kv-row"><span className="kv-label">Batch number</span><span className="kv-val lt-mono">{batch.batch}</span></div>
              <div className="kv-row"><span className="kv-label">Quantity</span><span className="kv-val">{batch.qty.toLocaleString()}</span></div>
              <div className="kv-row"><span className="kv-label">Manufacturing date</span><span className="kv-val">{batch.mfg}</span></div>
              <div className="kv-row"><span className="kv-label">Expiry date</span><span className="kv-val">{batch.expiry}</span></div>
              <div className="kv-row"><span className="kv-label">Generation level</span><span className="kv-val capitalize">{batch.generationLevel}-level</span></div>
              <div className="kv-row"> <span className="kv-label">MRP</span> <span className="kv-val">₹{batch.mrp?.toLocaleString() || "—"}</span> </div>
              <div className="kv-row"> <span className="kv-label">Created</span> <span className="kv-val"> {batch.created ? new Date(batch.created).toLocaleString() : "—"} </span> </div>
              <div className="kv-row"> <span className="kv-label">Created by</span> <span className="kv-val"> {batch.createdBy || "—"} </span> </div>
            </div>
            <div className="mt-5">
              <div className="text-xs font-bold uppercase tracking-wide text-faint mb-2.5"> Label information </div>
              <div className="kv-row"> <span className="kv-label">Labels generated</span> <span className="kv-val"> {batch.codesGenerated?.toLocaleString() || "0"} </span> </div>
              <div className="kv-row"> <span className="kv-label">Labels activated</span> <span className="kv-val"> {batch.codesActivated?.toLocaleString() || "0"} </span> </div>
              <div className="kv-row"> <span className="kv-label">Generated by</span> <span className="kv-val"> {batch.codesGenerated > 0 ? (batch.createdBy || "—") : "—"} </span></div>
            </div>
            </>
          )}
        </div>

        <div className="grid gap-3.5">

        {activationHistory.length > 0 && (
  <div className="card">
    <div className="text-xs font-bold uppercase tracking-wide text-faint mb-2.5">
      Activation History
    </div>

    {activationHistory.map((item, index) => (
      <div
        key={`${item.id}-${index}`}
        className="border-b border-line last:border-b-0 py-3"
      >
        <div className="kv-row">
          <span className="kv-label">Activated by</span>
          <span className="kv-val">
            {item.activatedBy || "—"}
          </span>
        </div>

        <div className="kv-row">
          <span className="kv-label">Activated at</span>
          <span className="kv-val">
            {item.when
              ? new Date(item.when).toLocaleString()
              : "—"}
          </span>
        </div>
      </div>
    ))}
  </div>
)}
        
        {recall && (
          <div className="card">
            <div className="text-xs font-bold uppercase tracking-wide text-faint mb-2.5"> Recall information </div>
            <div className="kv-row"> <span className="kv-label">Product name</span> <span className="kv-val"> {recall.productName || "—"} </span> </div>
            <div className="kv-row"> <span className="kv-label">Reason for recall</span> <span className="kv-val text-right max-w-[220px]"> {recall.reason || "—"} </span> </div> 
            <div className="kv-row"> <span className="kv-label">Recalled by</span> <span className="kv-val"> {recall.recalledBy || "—"} </span> </div>
            <div className="kv-row"> <span className="kv-label">Recalled at</span> <span className="kv-val"> {recall.date ? new Date(recall.date).toLocaleString() : "—"} </span> </div>
          </div>
        )}

        {anomaly && ( 
          <div className="card"> 
            <div className="text-xs font-bold uppercase tracking-wide text-faint mb-2.5"> Anomaly flag </div> 

            <div className="flex items-start gap-3"> 
              <div className="w-[30px] h-[30px] rounded-md flex items-center justify-center flex-shrink-0 bg-red-tint"> <AlertTriangle size={15} className="text-red" /> </div> 
              <div className="text-[13px] text-text"> {anomaly.text} </div> 
            </div> 
          </div> 
        )}
      </div>
      </div>
    </>
  );
}



